name: Bandit Security Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit Scan
        uses: shundor/bandit-action@v1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
