name: Bandit Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@v1.0

      - name: Upload Bandit results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
